---
title: "Statistical Disclosure Control - Microdata"
author: "Ben Cuff"
date: "30 September, 2022"    #"`r format(Sys.time(), '%d %B, %Y')`"
draft: false
output: 
  html_document:
    toc: true
    toc_depth: 3
    number_sections: false
    template: "../- assets/Templates/html_template.html"
  word_document:
    reference_docx: "../- assets/Templates/UKHSA plain document template.dotx"
knit: (function(inputFile, encoding){rmarkdown::render(inputFile, envir = globalenv(), encoding = encoding, output_dir = "./", output_format = "all")})


versioncontrol: "`r guidanceDocs::VersionHistory(  c('30/09/2022', 'Initial release')  )`"
---


```{r setup, echo=F, include=F}
library(tidyverse)
library(guidanceDocs)
knitr::opts_chunk$set(echo = F)

SetUpReferenceList("../- assets/QPD knowledge bank.xlsx")

```


## Coverage

This guidance applies to all external releases of microdata, defined as record-level data with each row defining an individual, or individual household or employer, for example^`r addRef(15)`^. 

This document should be seen as a supplement to our guidance on [statistical disclosure control for aggregate data](https://htmlpreview.github.io/?https://github.com/UKHSA-Statistics-Production/knowledge-hub/blob/main/Disclosure%20control/Disclosure-control-for-aggregate-data.html). Many of the same principles covered there apply to microdata as well and so shall only be repeated in brief here. As such, it is recommended that readers familiarise themselves with that guidance first.

Special data protection controls around the sharing of microdata are usually needed, such as data sharing agreements. This guidance assumes those controls are appropriately in place and they are not covered here. 

This guidance is not necessarily intended to replace any existing policies statistics producers may have in place that outline specific approaches for their outputs. It is intended to provide general guidance on this topic, in order to inform those policies, should producers wish to create them. 


## Summary of recommendations

1. A Responsible Statistician should ensure that the following steps are undertaken for all releases.
1. Prior to any release of microdata, a risk assessment should be conducted to determine the likelihood and impact of any disclosure risks. K-anonymity and intruder testing can be used for these purposes. 
1. Where a risk is identified, disclosure control methods should be applied, such as banding continuous variables, collapsing categorical variables, removing unnecessary variables, suppressing values, or removing unsafe records. The purpose of this is to reduce the disclosure risk to acceptable levels whilst maintaining utility of the release for users. 
1. After applying disclosure control methods, outputs should be re-assessed to ensure that risks have been successfully mitigated.


##Introduction

While data is more commonly released in aggregated formats, individual-level (micro) data can provide a rich opportunity for opening up access to the research community^`r addRef(15)`,`r addRef(10)`^. Compared to aggregate data, however, the fact that microdata is presented at that individual level means that there is a heightened risk that personal information might be disclosed. Strong controls are therefore needed to prevent identification^`r addRef(12)`^. 

As with aggregate data, if personal information is accidentally disclosed, that can cause harm and distress to data subjects, as well as reputational damage and legal implications for UKHSA^`r addRef(14)`^. Disclosure could occur both spontaneously or through motivated attacks, via the use of personal knowledge or linked datasets or other sources (for example, information found on social media platforms)^`r addRef(15)`^.

As with aggregate data, there is a need to balance disclosure control against utility^`r addRef(15)`,`r addRef(10)`^. A Responsible Statistician should be in place to ensure that balance is appropriately achieved^`r addRef(15)`^. The aim again here is to reduce risk to acceptable levels (such that it would take disproportionate time, effort and expertise to identify data subjects), while maintaining utility for users^`r addRef(15)`^. 


## Guidelines for identifying and controlling disclosure risk

The steps described here are much the same as those described in our guidance on [statistical disclosure control for aggregate data](https://htmlpreview.github.io/?https://github.com/UKHSA-Statistics-Production/knowledge-hub/blob/main/Disclosure%20control/Disclosure-control-for-aggregate-data.html). 
Some repeated information will only be covered briefly here. 

### Steps 1 to 3: Understanding your data and conducting a risk assessment

1. Determining user requirements
    a. The following questions might be considered. Who are your main users? What are your reasons for publishing this data? Why do users need this data and what do they intend to do with it? What level of detail is required to meet these needs?
    a. An understanding of who your intended users are and what they intend to do with your data is important in assessing risks and in determining which disclosure control methods would be acceptable to those users. In particular, it will help you understand what information would need to be retained in order for the release to still be useful for users. 
    
2. Understand the characteristics of the data and where disclosure risks may be present
    a. Many of the same risk factors given in our guidance on [statistical disclosure control for aggregate data](https://htmlpreview.github.io/?https://github.com/UKHSA-Statistics-Production/knowledge-hub/blob/main/Disclosure%20control/Disclosure-control-for-aggregate-data.html) will still apply here. Specifically, greater disclosure risks may be present when:
        * the data concerns more sensitive topics 
        * the data contains key identifying variables (for example, demographics, location, salary)
        * the data has been drawn from small populations
        * the data contains data subjects that are rare or unique within the dataset (although samples might carry a smaller risk here as users often cannot be sure a person was in the sample^`r addRef(12)`^)
        * it is likely that users might have personal knowledge or third-party datasets (such as the electoral register) available to them which can help them identify data subjects^`r addRef(15)`,`r addRef(13)`^
        * the data was collected recently
        
    a. Some more specific considerations might also be made in the case of microdata:
        i. Microdata might naturally contain direct identifiers such as name, postcode, NHS number, etc. In most cases it will be crucial that these are identified and removed prior to data release^`r addRef(15)`^.
        i. As data is presented at the level of individuals, the presence of key identifying variables (for example, age, sex, health condition, ethnicity, religion, martial status, among others)^`r addRef(13)`^ becomes all the more important, particularly when some combinations of characteristics might be rare or unique^`r addRef(15)`^. 
        i. The presence of longitudinal data might increase risk levels where changing characteristics might be disclosive^`r addRef(15)`^.

3. Assess the likelihood and impact of a disclosure risk
    a. The presence of the above factors will increase the likelihood and impact of disclosure risks. Rarity or uniqueness within the data is a particular risk factor that needs to be identified and addressed. 
    a. It is important to bear in mind that microdata will often be tabulated by users to get summary counts. While risks should ideally be identified and resolved on the microdata itself, it is worth also looking at tabulated versions of the data (for example, across key variables) to see if any additional risks do emerge^`r addRef(15)`,`r addRef(10)`^. 
    a. K-anonymity might be a useful method through which to identify rarity or uniqueness within the data, as described by NHS Digital^`r addRef(12)`^. The idea here is to ensure that there are at least 3 ('k=3') or 5 ('k=5') records in the data set for each combination of characteristics.<br>For example, if the data contains fields for age and gender, there should be at least 3 or 5 entries for every combination of age and gender. Where these thresholds are not met, disclosure control methods (described in the following section) should be applied until they are met. In effect, this is applying the same principles as for aggregate data, where it is recommended that tabulated cell values of less than 3 or less than 5 should be avoided.
        i. Where sensitivity and risk is relatively low, k=3 might be sufficient. This is termed 'weak' k-anonymity, and only key identifying characteristics need normally be controlled: for example, age, gender, ethnicity, location, 'event dates' (e.g., day admitted to hospital), employer, and occupation.
        i. Where sensitivity and risk is higher, k=5 might be needed ('strong' k-anonymity). More variables should be included in the k-anonymity test here, with the advice being to control for all variables but one (with that one variable not being a key identifying characteristic). 
    a. Intruder testing might be another useful method, as described by the Office for National Statistics^`r addRef(10)`^.<br>Intruder testing is performed by tasking 'intruders' (usually internal colleagues, but could be external people with strict controls in place) to try to identify individuals within the dataset. The ideal candidates for this testing are those that have some background knowledge of the data similar to that of a typical user and enough technical knowledge to do a thorough test, although they are not expected to be considered experts (for example, professional hackers).<br>Intruders could be given a list of names and asked to try to identify those individuals in the dataset. They would do that through the use of publicly available datasets and by searching the internet (for example, social media sites).<br>Where correct identifications are made, disclosure control should be applied to the data. Intruders should also be asked to record the logic and variables they used to make those identifications. In this way, intruder testing can supplement your risk assessments by giving you an understanding of where risks lie, and how a motivated individual might go about trying to identify data subjects. 
 

### Step 4: Choosing and applying disclosure control methods

The following steps should be taken in all cases, as they would always pose a disclosure risk:

a. Any direct identifiers (for example, name, NHS number) should always be removed from the data as these will clearly identify an individual^`r addRef(15)`,`r addRef(12)`^.

a. Other indirect identifiers such as exact date of birth and postcode should be reduced in detail^`r addRef(12)`^. If important for users, these could be truncated rather than being removed entirely^`r addRef(12)`^. The level of geography might also be increased, for example by presenting location at regional level rather than giving postcodes^`r addRef(15)`,`r addRef(13)`^. 

Note that pseudonymisation is sometimes used to mask directly identifiable information such as name, in a way that still allows for data to be associated with a particular individual without that individual being directly identified. However, there are still risks here as data is still presented in an individual-level format and pseudonymised values may still allow some linking between datasets. This could mean that pseudonymisation might be reversed, particularly for detailed datasets^`r addRef(16)`,`r addRef(35)`^. This method should therefore be employed cautiously, if at all.

Other key identifying variables (age, gender, etc.) might then be addressed to reduce the amount of risk, using one or more of the following methods. Other variables that are not necessarily identifiable may not need to be controlled for when risk levels are otherwise low^`r addRef(12)`^. Again, it is important to pay consideration to the user requirements here, which might mean applying different levels of disclosure control to different variables^`r addRef(15)`,`r addRef(16)`^. For example, it might be deemed important to have the exact age of data subjects, but to compensate for this risk, other variables could be collapsed and removed to add sufficient uncertainty elsewhere.

 
a. Continuous variables (such as age and height) can be banded into groups (for example, into 5-year age brackets instead of actual ages)^`r addRef(15)`,`r addRef(12)`,`r addRef(13)`,`r addRef(16)`^.
a. Categorical variables can be collapsed to reduce the level of detail^`r addRef(15)`,`r addRef(12)`,`r addRef(13)`,`r addRef(16)`^ (for example, by presenting broader occupational classifications rather than more specific job roles).
a. Problematic variables could be removed if they are not needed by users^`r addRef(15)`,`r addRef(12)`^.
a. Where there are individual 'combinations at risk' (in other words, where a data subject might be the only one with a certain set of characteristics), suppression could be used to hide an individual value^`r addRef(13)`,`r addRef(16)`^, replacing it with '[c]' (for confidential; square brackets are used to denote shorthand^`r addRef(54)`^). Note that it is important to apply this in such a way that the reason for suppression, and therefore the underlying value, is not made obvious ^`r addRef(13)`^. 
a. Problematic data subjects could be removed entirely^`r addRef(10)`,`r addRef(13)`,`r addRef(16)`^. However, you would need to consider the impact on utility here, including what effect this would have on summary counts or averages when the data is aggregated^`r addRef(16)`^. 


Other methods have been suggested, such as record swapping, micro-aggregation, and Barnardisation^`r addRef(16)`^. However, these are more destructive methods and might be more difficult to explain to users. As such, they might not be advisable in most cases. Please seek guidance from [UKHSA_HOPSTATS@ukhsa.gov.uk](mailto:UKHSA_HOPSTATS@ukhsa.gov.uk) if you are considering these methods. 


### Step 5: Assessing the outcome and disseminating

After choosing and applying a disclosure control method, outputs should be re-assessed to ensure that risks have been successfully mitigated^`r addRef(12)`^. This might include re-tabulating the data to check for small table cell values, re-checking that k-anonymity thresholds are being met, and re-conducting intruder testing exercises. 

It is good practice, where applicable, to explain as part of the data release that a disclosure risk has been identified and to explain what methods have been applied, including detail on the nature and extent of any modification^`r addRef(2)`^.

As a last resort solution, if no disclosure method would be successful in mitigating the risk (for example, because they would all be too detrimental to utility), there is the possibility of releasing potentially disclosive information under a 'Non-Disclosive Data Access Arrangement' (DAA)^`r addRef(5)`^. However, this should be done in very rare cases only, and only under the express permission of the [Head of Profession for statistics](mailto:UKHSA_HOPSTATS@ukhsa.gov.uk).


## Example risk assessment and disclosure control

The tables below report on some hypothetical data showing hospital admissions following infection according to different demographic characteristics. Let us assume that what is shown are the first 14 rows from a larger (again hypothetical) dataset containing more records, including different age groups. 


#### Table 1a. Hospital admissions

| Name               | NHS Number | Age | Postcode | Employment Status | Admission route |
|--------------------|------------|-----|----------|--------------------|-----------------|
| Taiba Jarvis       | 9018040287 | 18  | SO12 2LJ | Employed - Perm.   | GP              |
| Bartlomiej Dunkley | 2147012534 | 18  | SO15 5GR | Employed - Perm.   | GP              |
| Aiesha Read        | 0330525406 | 18  | SO5 0RQ  | Employed - Perm.   | GP              |
| Torin Wicks        | 3380320988 | 18  | SO8 2HX  | Employed - Perm.   | A&E             |
| Daniele Haigh      | 1399743438 | 18  | SO12 4LA | Employed - Perm.   | A&E             |
| Keri English       | 2386999155 | 18  | SO5 0BQ  | Employed - FTC     | GP              |
| Aarav Blanchard    | 6176053965 | 18  | SO13 9NH | Employed - FTC     | GP              |
| Elle-May George    | 7414048758 | 18  | SO42 1JA | Employed - FTC     | A&E             |
| Yolanda Pierce     | 1426716481 | 18  | SO4 1QB  | Unemployed         | GP              |
| Kira Gilmore       | 7470183044 | 18  | SO2 6DP  | Unemployed         | GP              |
| Gabriel Malone     | 1321629650 | 18  | SO11 1RP | Unemployed         | GP              |
| Muna Whitfield     | 9270240890 | 18  | SO10 9SA | Unemployed         | GP              |
| Jadon Mcgrath      | 6622466247 | 18  | SO5 4EY  | Unemployed         | GP              |
| Emir Ali           | 3052768761 | 18  | SO18 6BX | Unemployed         | A&E             |
| ...                | ...        | ... | ...      | ...                | ...             |


A number of risks exist here. Most obviously, name and NHS number are direct identifiers, and must be removed. Postcode is also an indirect identifier, which should be looked at. 

Setting aside postcode, tabulating this data would highlight the fact that there are a number of combinations of characteristics that would not meet the k=3 k-anonymity threshold. For example, there are only two individuals employed on permanent contracts that were admitted via A&E. Emir Ali (at the bottom of Table 1a) is also unique in being the only unemployed individual that was admitted via Accident and Emergency.  


#### Table 1b. Hospital admissions - disclosure control applied

| Age | Region     | Employment Status | Admission route |
|-----|------------|-------------------|-----------------|
| 18  | South East | Employed          | GP              |
| 18  | South East | Employed          | GP              |
| 18  | South East | Employed          | GP              |
| 18  | South East | Employed          | A&E             |
| 18  | South East | Employed          | A&E             |
| 18  | South East | Employed          | GP              |
| 18  | South East | Employed          | GP              |
| 18  | South East | Employed          | A&E             |
| 18  | South East | Unemployed        | GP              |
| 18  | South East | Unemployed        | GP              |
| 18  | South East | Unemployed        | GP              |
| 18  | South East | Unemployed        | GP              |
| 18  | South East | Unemployed        | GP              |
| [c] | South East | Unemployed        | A&E             |
| ... | ...        | ...               | ...             |


The following series of steps were taken to address most of the risks present in Table 1a, to produce Table 1b:

1. Name and NHS number fields were removed as they are direct identifiers.
1. Postcodes have been transformed into regions to increase the population at risk for the geographical areas presented.
1. Employment status has been collapsed into 2 categories rather than 3 (we can assume this would be acceptable to users).
1. Emir Ali's uniqueness has been masked by suppressing their age, giving a '[c]' (for confidential; square brackets are used to denote shorthand^`r addRef(54)`^) instead. This introduces sufficient uncertainty when presented along with the other ages assumed to be present in the full dataset.<br>Suppressing Emir's employment status or admission route instead might not have been advisable, because most unemployed 18 year olds were admitted via their GPs. It might be obvious that any suppression within these fields might have been done to mask the fact that Emir was unique in being unemployed and admitted via A&E.

In this new table, all combinations of characteristics that are present in the data now meet the k=3 k-anonymity threshold. 

However, with Emir's age suppressed, there is a new risk here that users might perceive a group disclosure that all unemployed data subjects were admitted via their GPs. As such, it might be worth exploring whether the employment status field is necessary or whether it could be removed. Another option would be to present age bands instead of absolute ages, assuming that enough data subjects in the same band would be unemployed and admitted via the A&E route. 


## References

`r AddReferenceList()`